name: dbt-elementary
version: "0.1.0"
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

profile: local

model-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dbt-elementary:
    +enabled: "{{ env_var('STORE_TEST_RESULTS', 'false') == 'true' }}"
    +meta:
      schema_name: "matatika_test_results"

vars:
  schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"

tests:
  +schema: matatika_test_results
